# -*- coding: utf-8 -*-
"""Capitulo3_labo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pW9rCIqxvfh2C5DNnoy1iMZx8Vp5-zaF
"""



"""**1. Instalación**
!pip install pandas

**2.Series**
"""

import pandas as pd

obj = pd.Series([4, 7, -5, 3])
print(obj)

obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)

print(obj2['a'])

#condicional
print(obj2[obj2 > 0])

"""4.Series desde **diccionario**"""

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(obj3)

"""**5. Crear DataFrame**"""

data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001,2002,2003],
    'salario': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
print(frame)

pd.DataFrame(data, columns=['year', 'state', 'salario'])

frame['debt'] = list(range(6))
print(frame)

data_values = [
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15],
]

index = ['Ohio', 'Colorado', 'Utah', 'New York']
columns = ['one', 'two', 'three', 'four']

df = pd.DataFrame(data_values, index=index, columns=columns)
print(df)
print('\n')
df = df.drop(['Colorado','Ohio'])
print(df)
df.drop('three', inplace=True, axis= 1) # inplace=True, axis= 1
print('\n')

print(df)
print('\n')
df[:2]

import pandas as pd

data = {
    "Departamento": ["Lima", "Cusco", "Arequipa", "Ica"],
    "Poblacion (miles)": [9485, 1205, 1382, 1172]
}

df = pd.DataFrame(data)
print(df)
print('\n')
#total
total = df["Poblacion (miles)"].sum()

#promedio
promedio = df["Poblacion (miles)"].mean()
print('\n')
print(f"Total de población: {total}")
print('\n')
print(f"Promedio de población: {promedio}")
print('\n')
print(df[df["Poblacion (miles)"] > 1300])

import pandas as pd
import numpy as np

data = {
    "Nombre": ["Juan", "María", "Pedro", "Ana","Emily"],
    "Score": [12.5, 9.0, 16.5, np.nan, 9.0],
    "Genero": ["M", "F", "M", "F","F"],
    "Quality": ["yes","no","yes","no","no"]
}

df = pd.DataFrame(data)
print(df)
print('\n')
grupo = df.groupby("Quality")["Nombre"].count()
print(grupo)

calificados = df[df["Quality"] == "yes"]
print(calificados)

"""Columna **calculada**"""

df["Score_x"] = df["Score"] * 1.2
print(df)

#Cloud --- nube AWS por ejemplo:   PySpark
#Gestión de Datos --- Pandas y Maptploit   ......
#Automatizaciones --- Pandas, selenium (scrapear paginas web), ...
#Machine learning e IA