# -*- coding: utf-8 -*-
"""Capitulo3_labo2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5yHIJEAO4nh-tCAdwH7zzV0b8ZWTnqT
"""

##seguimos 29 de marzo ##########################################
import pandas as pd 

peru_df = pd.read_excel('peru_df.xlsx')
#peru_df = peru_df.set_index('dep')
peru_df

peru_df.dtypes

print(peru_df.columns)

print(peru_df.axes)

print(peru_df.values)

peru_df_ordenado = peru_df.sort_values(by=['dep'])
peru_df_ordenado

import random

peru_df['pbi'] = [random.randint(100000,1000000) for e in range(len(peru_df))]
print(peru_df)

peru_df[['pob','pbi']].agg(['min','max','mean'])
new_peru_df = peru_df

new_peru_df.to_excel("new_peru_df.xlsx")