# -*- coding: utf-8 -*-
"""Capitulo_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFeUT3yAllsCXZ2D_uZS06C1qiksZ-_e
"""

import pandas as pd

datos = {
    "Nombre": ["Ana","Luis","Maria","Leo","Carla","Lucia"],
    "Edad": [25,30,35,40,45,50],
    "Ciudad": ["Lima","Arequipa","Buenos Aires","Sao Paulo","Londres","Caracas"]
}

df =pd.DataFrame(datos)
print(df)
print('\n')
print(df.head()) # Muestra los 5 primeros registros
print('\n')
print(df.tail()) # Muestra las últimas 5 filas
print('\n')
print(df.info()) # información del df
print('\n')
print(df.describe) # resumen estadístico del df

print(df["Nombre"])

print(df[["Nombre","Edad"]])

print(df.iloc[0])

print(df.iloc[0:2])   #iloc  trabaja por posición numérica

print(df[df["Edad"] > 40])  # Aqui pandas revisa fila por fila y solo muestra las que cumplen la condición

print(df[df["Ciudad"] == "Lima"])

print(df[(df["Ciudad"] == "Lima") | (df["Edad"] > 40)])  # |: Operador o

df.loc[0,"Ciudad"] = "Trujillo"
print(df)

import matplotlib.pyplot as plt

x = [1,2,3,4,5]
y = [10,20,25,40,55]

plt.plot(x,y)
plt.title("Ventas por mes")
plt.xlabel("Mes")
plt.ylabel("Ventas")
plt.show()

categorias = ["A","B","C","D"]
valores = [100,200,150,350]

plt.bar(categorias,valores)
plt.title("Ventas por categoría")
plt.xlabel("Categoría")
plt.ylabel("Ventas")
plt.show()

#Histograma:  Muestra distribución de datos

datos = [10,20,20,30,40,40,40]
plt.hist(datos)
plt.show()

#Dispersión Muestra la relación entre variables

x = [1,2,3,4,5]
y = [10,20,25,40,55]

plt.scatter(x,y)
plt.show()