# -*- coding: utf-8 -*-
"""Pokémon_taller_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECiRRIyV3gYC3Acn6uHlb-0APOIt-Uyn

# Taller de Análisis Exploratorio de Datos en Python

## Sesión 1

### Estadística y Análisis Exploratorio de Datos

- La estadística es la ciencia que se ocupa de desarrollar y estudiar modelos para recolectar, analizar, interpretar y presentar datos.

- EDA:
    - Primer paso en cualquier proyecto de Data Science, y se basa en conceptos de estadística descriptiva.
    - El EDA tiene valor por si mismo, y es posible llegar a conclusiones sobre los datos sin la necesidad de utilizar algoritmos más complejos.

    - Ayuda al entendimiento entendimiento de los datos y ver la forma y características de los mismos. Este entendimiento es fundamental antes de pensar en implementar algún modelo.

![EDA.png](attachment:EDA.png)

### Conceptos importantes de Estadística

- Población: Colección específica de objetos de interés.
- Muestra: Subconjunto de una población, puede o no ser ’representativa’. Los elementos de la muestra se llaman observaciones.
- Unidad de observación: Se refiere al elemento sobre el cual se quieren responder una o varias preguntas.
![Population,%20sample%20and%20observational%20unit.jpg](attachment:Population,%20sample%20and%20observational%20unit.jpg)
- Atributo o variable: Descripción de las observaciones en una característica específica. Pueden ser de tipo cuantitativo (numérico) o cualitativo (categórico).
![Quantitative%20and%20qualitative%20data.png](attachment:Quantitative%20and%20qualitative%20data.png)
- Estadístico o medida: Es un número que se usa para resumir y describir a todas las observaciones en algún atributo específico.
![Statistic.PNG](attachment:Statistic.PNG)

### Cargar los datos

Como primera parte del análisis se cargan las librerias necesarias, este taller se va a basar especialmente en funcionalidades de la libreria "pandas". La documentación de esta libreria donde se incluyen todos los métodos y funciones que se usan en este documento se encuentra en el siguiente enlace: https://pandas.pydata.org/pandas-docs/stable/
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
# %matplotlib inline

"""Se carga el archivo de datos usando la función <strong>"read_csv()"</strong>. En este caso solo es necesario especificar el directorio que contiene el archivo, pero en algunas ocasiones resulta de utilidad especificar otros parámetros."""

pokemon = pd.read_csv('pokemon.csv')


"""El archivo se carga como un DataFrame de pandas, está es la estructura más utilizado para realizar análisis de datos en Python, es una estructura de forma tabular donde cada fila pertenece a una observación y cada columna corresponde a un atributo de las observaciones. El método <strong>".head()"</strong> nos permite ver una cantidad específica de filas del DataFrame."""

type(pokemon)

pokemon.columns

pokemon.head(10)

"""### Seleccionar variables

El atributo <strong>".columns"</strong> se utiliza para obtener los nombres de las variables del DataFrame.
"""

pokemon.columns

"""Para seleccionar variabes o alterar su orden en el DataFrame se utiliza la sintaxis mostrada en la siguiente celda, que básicamente consiste del nombre del DataFrame, un par de paréntisis cuadrados y dentro de estos una lista que contenga el nombre de las variables que se quiera seleccionar en el orden deseado."""
print(pokemon.columns)
pokemon.columns = pokemon.columns.str.lower().str.replace(" ", "_").str.replace(".", "")
print(pokemon.columns)
pokemon = pokemon[['name', 'type_1', 'type_2', 'total', 'hp', 'attack', 'defense',
       'sp_atk', 'sp_def', 'speed', 'generation', 'legendary']]

"""El DataFrame ahora consiste únicamente de las variables seleccionadas anteriormente."""

pokemon.head(9)
print(pokemon.head(9))

"""En este caso se selecciona únicamente el nombre del pokémon y su respectiva defensa, además se limita a los primeros 9 de la base que dado a que están ordenados por sunúmero de Pokédex son los iniciales de la primera generación."""

pokemon[['name', 'defense']].head(9)

"""### Filtrar observaciones

Para filtrar observaciones dependiendo de sus valores en ciertas variables la sintaxis es similar a la utilizada para seleccionar variables, primero se especifica el nombre del DataFrame, luego paréntesis cuadrados y dentro de estos se especifican las condiciones a cumplir.

Para las condiciones se seleccionan las variables que deben de cumplir la condición de la misma manera que seleccionamos variables anteriormente.

En este caso estamos seleccionando los pokémones de tipo eléctrico de la tercera generación.
"""

pokemon[(pokemon['type_1'] == 'Electric') & (pokemon['generation'] == 3)]

"""También es posible seleccionar variables y filtrar observaciones en un solo comando, en este caso los primeros paréntesis cuadrados se utilizan para seleccionar las variables deseadas y a continuación se abre otro par para realizar la filtración de las observaciones."""

pokemon[['name', 'defense']][(pokemon['type_1'] == 'Electric') & (pokemon['generation'] == 3)]

"""El mismo resultado se puede obtener usando el atributo <strong>".loc"</strong> en el cual solo se necesita un par de paréntesis cuadrados, donde primero se especifican las condiciones para filtrar las observaciones y luego, separado por una coma se adiciona una lista con las variables a seleccionar."""

pokemon.loc[
    (pokemon['type_1'] == 'Electric') & (pokemon['generation'] == 3),
    ['name', 'defense']
]
"""### Medidas de Centralidad

La media o promedio es la medida de centralidad más conocida y utilizada, su fórmula es la siguiente:

![image.png](attachment:image.png)

Para calcular la media en Python se seleccionan la(s) variable(s) y se usa el método <strong>".mean()</strong>"
"""

pokemon['speed'].mean()

pokemon[['attack', 'defense']].mean()

"""La mediana corresponde al dato, tal que, el 50% de las observaciones son menores o iguales a este y el 50% son mayores o iguales a este dato.

Para su cálculo se ordenan todos los datos y se selecciona el que esté exactamente en la mitad.

Su cálculo en Python es básicamente igual al de la media a excepción de que se utiliza el método <strong>".median()"</strong>.

En este ejemplo se puede decir que el 50% de los pokémones tienen un ataque menor o igual a 75 y el otro 50% tiene un ataque mayor o igual a 75.
"""

pokemon[['attack', 'defense']].median()

"""Los cuantiles se interpretan de manera similar a la mediana, de hecho la mediana es un cuantil específico (50), por ejemplo, el cuantil 25 se interpreta como que el 25% de las observaciones son menores o iguales a este.

Para su cálculo en Python se utiliza el método <strong>".quantile()"</strong> y se específica una lista con los cuantiles deseados en forma de proporción (0.25 equivale a 25% por ejemplo).

En este caso el 25% de los pokémones tiene un ataque menor o igual a 55, también el 75% de los pokémones tiene un ataque menor o igual a 100.

![download1.png](attachment:download1.png)
"""

pokemon[['attack', 'defense']].quantile([0.25, 0.75])

"""La moda de un atributo es el valor más repetido entre todas las observaciones. Esta medida se puede utilizar tanto en variables numéricas como categóricas."""

pokemon[['attack', 'defense']].mode()

"""El método <strong>".idxmax()"</strong> se puede utilizar para obtener el índice de la observación con el valor más alto en algún atributo.
El atributo <strong>".iloc"</strong> funciona para indexar un DataFrame utilizando el número de filas o columnas.
En este caso obtenemos que Kyogre es el pokémon de tipo agua con el ataque especial más alto.
"""

index = pokemon.loc[pokemon['type_1'] == 'Water', 'sp_atk'].idxmax()
pokemon.iloc[index]

"""El método <strong>".max()"</strong> devuelve el valor más alto en las variables específicadas.
En este caso vemos que el valor más alto en puntos de salud entre pokémones con una altura menor o igual a 0.5 metros que no sean legendarios es de 115.
"""

pokemon.loc[pokemon['legendary'] == False, 'hp'].max()

"""Si usamos <strong>".idxmax()"</strong> como la habíamos hecho anteriormente nos damos cuenta que el pokémon con ese valor de puntos de salud es Jigglypuff."""

pokemon.loc[pokemon['legendary'] == False, 'hp'].max()
pokemon.iloc[index]

"""Los métodos <strong>".min()"</strong> y <strong>".idxmin()"</strong> funcionan de la misma manera que <strong>".max()"</strong> y <strong>".idxmax()"</strong> respectivamente, con la diferencia que estos buscan por el valor más bajo en lugar del más alto.

### Distribuciones de frecuencias y tablas cruzadas

Las distribuciones de frecuencias y tablas cruzadas son métodos que funcionan para ver el comportamiento de variables catégoricas univariada o bivariadamente.

Una distribución de frecuencias es una tabla que indica el número de casos que se tiene en cada una de las categorías de la variable.

En pandas una distribución de frecuencias se obtiene al utilizar el método <strong>".value_counts()"</strong> luego de seleccionar la(s) variable(s) a tabular.

En esta distribución de frecuencias podemos observar que los tipos más frecuentes en la primera generación son el tipo agua y tipo normal y los menos frecuentes el tipo hada y tipo hielo.
"""

pokemon.loc[pokemon['generation'] == 1, 'type_1'].value_counts()

"""Si se agrega el parámetro "normalize = True" la distribución de frecuencias pasa a proporciones, las cuales multiplicadas por 100 se vuelven porcentajes."""

pokemon.loc[pokemon['generation'] == 1, 'type_1'].value_counts(normalize = True) * 100

"""Una tabla cruzada es similar a una distribución de frecuencias con la diferencia de que en la tabla cruzada se obtiene el comportamiento de ambas variables dentro de las categorías de la otra. Por ejemplo, la primera fila de la tabla cruzada que se muestra corresponde a la cantidad de pokémon de tipo insecto en las distintas generaciones. La primera columna corresponde a la distribución de frecuencias que mostramos anteriormente.

En pandas una tabla cruzada se construye usando la función <strong>"pd.crosstab()"</strong> a la que se le debe brindar las dos variables a tabular. El parámetro "margins = 1" agrega la última fila y la última columna correspondientes a los totales.
"""

pd.crosstab(pokemon['type_1'], pokemon['generation'], margins = 1)

"""### Medidas de dispersión

La dispersión de los datos indica que tan heterogeneos son los datos que se están analizando, esto quiere decir que tanto varían las observaciones unas de otras.

![image.png](attachment:image.png)

La desviación estándar puede ser interpretada como la diferencia promedio de las observaciones respecto a su media, la fórmula de cálculo es la siguiente:

![image.png](attachment:image.png)

En pandas esta medida se calcula con el método <strong>".std()"</strong>.
"""

pokemon[['sp_atk', 'hp']].std()

"""El rango intercuartil corresponde a la diferencia entre el cuantil 75 y el cuantil 25. Entre más variabilidad tenga la distribución de los datos esta medida será mayor.

No hay una forma directa de calcular esta medida en pandas, pero usando el método <strong>".quantile()"</strong> se puede hacer fácilmente.
"""

pokemon[['sp_atk', 'hp']].quantile(0.75) - pokemon[['sp_atk', 'hp']].quantile(0.25)

"""Con ayuda de los histogramas podemos visualizar la diferencia en la dispersion entre el ataque especial y los puntos de salud, la cual se observa mayor en el ataque especial, lo cual apoya lo que obtuvimos al calcular las medidas de dispersión.

También ayuda a visualizar la presencia de algunos valores especialmente altos en los puntos de salud, lo cual explicaría porque la diferencia en la variabilidad se visualiza más claramente utilizando el rango intercuartil que al utilizar la desviación estándar.

El código para construir este tipo de gráficos y otros se revisará a fondo en la sesión 2 del taller.
"""

pokemon['sp_atk'].plot(kind = 'hist', bins = 25, xlim = [0, 250], ylim = [0, 135], title = 'Distribution of Special Attack')
plt.xlabel('Special Attack')
plt.show()

pokemon['hp'].plot(kind = 'hist', bins = 30, xlim = [0, 250], ylim = [0, 135], title = 'Distribution of Health Points')
plt.xlabel('Health Points')
plt.show()

"""Nota: En la práctica, se suele usar el método .describe() que resume medidas sobre variables cuantitativas

"""

pokemon[['attack', 'defense']].describe()

"""### Crear nuevas variables

Para crear una nueva variable basta con asignar a una columna del DataFrame que aún no exista alguna operación basada en otros atributos de este o al menos que retorne el mismo número de observaciones.

En este caso se crea la variable "total", que corresponde a la suma de los 6 atributos de pelea.
"""

pokemon['total'] = pokemon[['hp','attack','defense','speed','sp_atk','sp_def']].sum(axis = 1)

pokemon.head(9)

"""Ahora esta nueva variable puede ser utilizada al igual que cualquier otra, como por ejemplo, para identificar al pokémon con el valor más alto en este atributo.

En este caso obtenemos que ese pokémon es Mewtwo.
"""

index = pokemon['total'].idxmax()
pokemon.iloc[index]

"""### Agregaciones

Las agregaciones son una manera de analizar variables numéricas dentro de las categorías de una variable categórica. Por ejemplo, aquí observamos la media del ataque especial(variable numérica) dentro de cada uno de los diversos tipos(variable categórica).

La sintáxis a utilizar comienza aplicando el método <strong>".groupby('variable categórica')"</strong>, luego se selecciona la(s) variable(s) numérica(s) a analizar y por último el método específico a la medida de resumen que se desea.
"""

pokemon.groupby('type_1')['sp_atk'].mean()

"""Otro método de utilidad es <strong>".sort_values()"</strong>, el cual ordena las observaciones de acuerdo a su valor lo cual ayuda a visualizar más fácilmente los resultados obtenidos.

Esto nos permite ver con facilidad que los pokémones del tipo psíquico y dragón son los que tienen en promedio un mayor ataque especial, y por contrario, los de tipo tierra y lucha presentan el menor valor en esta característica.

El parámetro "ascending = False" ordena los datos del mayor al menor.
"""

pokemon.groupby('type_1')['sp_atk'].mean().sort_values(ascending = False)

"""## Sesión 2

### Visualización de datos

La visualización de datos es definida como el uso de símbolos y estímulos visuales para facilitar la interpretación y el descubrimiento de patrones dentro de los datos. Es una habilidad fundamental dentro del análisis de datos ya que mediante el uso de visualizaciones es posible encontrar tendencias en los datos que de otra forma hubieran sido sumamente complicadas de identificar.

En este taller se van a exponer algunos de los tipos de gráficos más utilizados(histogramas, gráficos de densidad, gráficos de dispersión, gráficos de barras, gráficos de caja y gráficos de línea) de los cuales se abordará: el tipo de datos para los que se deben de utilizar, elementos importantes para su debida presentación y su interpretación.

### Histogramas

Los histogramas son un tipo de gráfico que resulta útil para visualizar la distribución de una variable cuantitativa. Este consiste de una serie de barras cuya altura indica la cantidad de observaciones dentro de un segmento de la variable continua. Este gráfico permite observar la tendencia de centralidad, la dispersión y la simetría de la variable.

La forma más básica de realizar un gráfico usando pandas es con el atributo <strong>".plot"</strong> usado en un DataFrame, luego de este atributo se utiliza el método correspondiente al tipo de gráfico que se desea realizar, en el caso de los histogramas se usa <strong>".hist()"</strong>. Es de utilidad seleccionar previo a la construcción del gráfico la columna que se desea graficar.
"""

pokemon['attack'].plot.hist()

plt.show()

"""Una característica deseable de cualquier gráfico es que estos deben de poder ser entendidos por cualquier persona sin necesidad de ninguna aclaración adicional, para esto hay algunos elementos básicos que se deben de agregar a todo gráfico para mejorar su presentación. Entre ellos están las etiquetas de los ejes y el título, estos se agregan respectivamente con las funciones <strong>"plt.xlabel()"</strong>(para el eje x), <strong>"plt.ylabel()"</strong>(para el eje y) y <strong>"plt.title()"</strong>, plt es el alias que se le dio al módulo pyplot de la librería matplotlib, la cual es la librería más conocida para visualización de datos en Python. En este taller usamos las funcionalidades de graficación de pandas ya que estas son más simples y además son un buen punto de partida para aprender otras más avanzadas."""

pokemon['attack'].plot.hist()
plt.xlabel('Attack')
plt.title('Distribution of attack')

plt.show()

"""Un detalle que siempre debe de ser tomado en cuenta a la hora de construir un histograma es la cantidad de barras que se van a utilizar en el gráfico, ya que, si se usa una cantidad muy alta el gráfico va a ser tan detallado que se puede perder la tendencia general de los datos, o si, por el contrario, se utilizan muy pocas columnas se pueden sobre simplificar los datos.

No hay una fórmula general para seleccionar el número de barras a utilizar, por lo que se recomienda es probar con varios números hasta obtener un resultado satisfactorio.

La cantidad de barras se selecciona con el parámetro "bins".
"""

pokemon[['attack']].plot.hist(bins = 50, legend = False)
plt.xlabel('Attack')
plt.title('Distribution of attack (50 bins)')
pokemon[['attack']].plot.hist(bins = 15, legend = False)
plt.xlabel('Attack')
plt.title('Distribution of attack (15 bins)')
pokemon[['attack']].plot.hist(bins = 5, legend = False)
plt.xlabel('Attack')
plt.title('Distribution of attack (5 bins)')

plt.show()

"""Algunas otras habilidades que pueden ayudar a darle formato a un gráfico son escoger los colores a utilizar en cada figura del gráfico así como agregar líneas para seleccionar algún valor específico de la distribución.

Para seleccionar los colores a utilizar en una figura se debe de crear un "colormap" de matplotlib, esto se logra utilizando la función <strong>"matplotlib.colors.ListedColormap()"</strong> a la cuál se le brinda una lista indicando los colores a utilizar, que en este caso es únicamente el color negro.

Para agregar líneas verticales al gráfico se usa la función <strong>"plt.axvline()"</strong>, la cuál tiene dos parámetros, "x" que se utiliza para especificar el valor en el eje x sobre el cuál se desea trazar la línea y "c" que específica el color que debe de tener la línea. Si se desea una línea horizontal se debe utilizar la función <strong>"plt.axhline()"</strong> y en lugar de parámetro "x" se usa el parámetro "y" para especificar la ubicación de la línea en el eje y.
"""

cmap = matplotlib.colors.ListedColormap(['black'])
pokemon['attack'].plot.hist(bins = 15, cmap = cmap)
plt.axvline(x = pokemon['attack'].quantile(0.25), c = 'red')
plt.axvline(x = pokemon['attack'].quantile(0.50), c = 'red')
plt.axvline(x = pokemon['attack'].quantile(0.75), c = 'red')
plt.axvline(x = pokemon['attack'].mean(), c = 'green')
plt.xlabel('Attack')
plt.title('Distribution of attack')

plt.show()

"""Si se quiere comparar la distribucion de una variable para dos poblaciones distintas se pueden sobreponer los dos histogramas en una misma figura, en este caso es muy importante usar colores distintos en cada histograma y agregar una leyenda. La leyenda se agrega con el parámetro "legend" dentro de la función que construye el histograma y se puede modificar utilizando la función <strong>"plt.legend()"</strong> donde se puede indicar el título(title), las etiquetas(labels) y la localización dentro del gráfico(loc).

Cuando se hace algún tipo de gráfico sobrepuesto es importante especificar el parámetro "alpha" a algún valor entre 0 y 1, esto con el fin de agregar transparencia a las figuras.
"""

cmap1 = matplotlib.colors.ListedColormap(['blue'])
cmap2 = matplotlib.colors.ListedColormap(['black'])
pokemon.loc[pokemon['generation'] == 1, 'attack'].plot.hist(bins = 10, cmap = cmap1, alpha = 0.5, legend = True)
pokemon.loc[pokemon['generation'] == 3, 'attack'].plot.hist(bins = 10, cmap = cmap2, alpha = 0.5, legend = True)
plt.legend(title = 'Generation', labels = ['1st', '3rd'], loc = 'center right')
plt.xlabel('Attack')
plt.title('Distribution of attack between the 1st and 3rd generation')

plt.show()

"""### Gráfico de dispersión

Los gráficos de dispersión son de utilidad para observar la distribución conjunta de dos variables cuantitativas y la relación que hay entre ellas. Este consiste de una serie de puntos cuya ubicación depende de los valores de cada observación en las dos variables analizadas.

El método utilizado para construir este tipo de gráfico es <strong>".scatter()"</strong> al cuál se le debe de brindar la variable a graficar en el eje x y en el eje y.

A continuación se realiza el gráfico de dispersión entre la altura y el peso de cada pokémon.
"""
"""
#pokemon.plot.scatter(x = 'height_m', y = 'weight_kg')
plt.xlabel('Height(m)')
plt.ylabel('Weight(kg)')
plt.title('Height and weight')

plt.show()

A veces puede ser de utilidad hacer zoom sobre algún área específica en el gráfico. En el caso anterior resultaría de utilidad enfocarse en el área donde se encuentra la mayoría de los puntos.

Esto se consigue usando los parámetros "xlim" y "ylim" a los cuales se les da una lista de tamaño 2 con el valor mínimo y máximo que se quiere para el eje x y el eje y respectivamente.

Al hacer esto se aprecia con más claridad que hay una relación entre ela altura y el peso de los pokémon, ya que a mayor altura el peso también tiende a aumentar.


pokemon.plot.scatter(x = 'height_m', y = 'weight_kg', xlim = [0, 6], ylim = [0, 400])
plt.xlabel('Height(m)')
plt.ylabel('Weight(kg)')
plt.title('Height and weight')

plt.show()
"""
"""Si se desea agregar una tercera variable a un gráfico de dispersión esto se puede lograr coloreando los puntos del gráfico de acuerdo a esta variable. Para lograr esto se utiliza el parámetro "c", cuando se hace esto es importante especificar adicionalmente el parámetro cmap, para esto se puede utilizar alguno de los colormap que vienen incluidos en matplotlib, la lista completa se encuentra en: https://matplotlib.org/users/colormaps.html.

Al agregar la variable ataque al gráfico vemos que los pokemones con mayor altura y mayor peso también suelen tener un mayor ataque.
"""
"""
pokemon.plot.scatter(x = 'height_m', y = 'weight_kg', c = 'attack', cmap = 'inferno',
                     figsize = (10, 5), xlim = [0, 6], ylim = [-10, 400])

plt.xlabel('Height(m)')
plt.ylabel('Weight(kg)')
plt.title('Attack related to height and weight')

plt.show()

### Gráfico de pastel

Un gráfico de pastel se usa para representar la distribución de frecuencias de una variable categórica. Este gráfico consiste de un círculo el cuál se divide en porciones para cada categoría dependiendo de la cantidad de datos pertenecientes a cada categoría.

El método en pandas para construir este tipo de gráfico es <strong>".pie()"</strong>.

Dado que este gráfico representa una distribución de frecuencias, en lugar de aplicar el método directamente al DataFrame como en los gráficos anteriores, resulta más simple primero calcular la distribución de frecuencias usando <strong>".value_counts()</strong> y luego aplicar el método a esta.


freq = pokemon['generation'].value_counts(normalize = True, sort = False) * 100

freq.plot.pie()
plt.ylabel('Generation')
plt.title('Frequency distribution for generation')

plt.show()
"""
"""Cuando no hay un orden lógico en las categorías de la variable para la que se construye el gráfico de pastel es importante para ayudar en la visualización que las porciones del gráfico se ordenen según su tamaño, al usar <strong>.value_counts()</strong> esto se hace automáticamente, por ese motivo en el gráfico anterior se definió el parámetro "sort" como False.

Respecto a la definición de colores esta se puede hacer ya sea usando su nombre en HTML o con el código hexadecimal. Para este gráfico saqué los colores del siguiente enlace: https://htmlcolorcodes.com/.

Por último, el método <strong>".str.capitalize()"</strong> se usa para que los tipos de pokémon se muestren con mayúscula.

Este gráfico ayuda a observar que los 4 tipos con más pokemones en la primera generación(agua, normal, veneno y planta) acumulan aproximadamente la mitad del total de los pokemones de esa generación.
"""

freq = pokemon.loc[pokemon['generation'] == 1, 'type_1'].value_counts(normalize = True) * 100
freq.index = freq.index.str.capitalize()
cmap = matplotlib.colors.ListedColormap(['blue', '#DCDABC', 'purple', 'green', 'olive', 'red', 'yellow', '#C4C073', '#C9C45A',
                                         'fuchsia', 'maroon', 'navy', '#4A235A', 'aqua', 'pink'])

freq.plot.pie(cmap = cmap, legend = True, fontsize = 0, figsize = (7, 7))
plt.ylabel('')
plt.legend(title = 'Type')
plt.title('Frequency distribution for type in the 1st generation')

plt.show()

"""### Gráfico de barras

Los gráficos de barras se pueden utilizar al igual que los gráficos de pastel para representar la distribución de variables de tipo categórico, además se puede usar para expresar variables numéricas agregadas por alguna variable categórica. En este gráfico la longitud de las diversas barras indica la magnitud de alguna característica para cada categoría.

Hay dos métodos para realizar este tipo de gráfico <strong>".bar()"</strong> y <strong>".barh()"</strong> para construir gráficos de barra verticales u horizontales respectivamente. La decisión de usar gráficos verticales u horizontales depende de las etiquetas de las categorías, si estas son números es correcto usar barras verticales, si son palabras se debe de usar barras horizontales para evitar que las etiquetas se sobrepongan.

Para estos gráficos también resulta útil construir primero la distribución de frecuencia o la agregación y aplicar el método en estas.

Este gráfico muestra la misma información que el primer gráfico de pastel mostrado anteriormente, la ventaja que tiene un gráfico de barras es que es más fácil hacer comparaciones entre las diversas categorías, mientras que la ventaja del gráfico de pastel es que muestra la importancia de cada categoría dentro del todo.
"""

freq = pokemon['generation'].value_counts(sort = False)
cmap = matplotlib.colors.ListedColormap(['black'])
freq.plot.bar(rot = 0, cmap = cmap)
plt.xlabel('Generation')
plt.ylabel('Number of Pokémon')
plt.title('Number of Pokemon for each generation')

plt.show()

"""Al igual que en el caso de los gráficos de pastel, en los gráficos de barras es importante que las categorías estén ordenadas de manera lógica, o si esta manera no existe, que se ordenen de la barra más larga a la más corta.

En el caso de este gráfico lo que se tiene es la media del ataque especial agregada por tipo de pokémon.
"""

agg = pokemon.groupby('type_1')['sp_atk'].mean().sort_values()
agg.index = agg.index.str.capitalize()
cmap = matplotlib.colors.ListedColormap(['black'])
agg.plot.barh(cmap = cmap, figsize = (8, 8))
plt.ylabel('Type')
plt.xlabel('Average special attack')
plt.title('Average special attack for each type of Pokémon')

plt.show()

"""Los siguientes dos gráficos van a presentar la siguiente tabla cruzada, que corresponde a la cantidad de pokemones de tipo planta, fuego y agua dentro de cada generación, esto se va a realizar utilizando dos tipos específicos de gráfico de barra: barras comparativas y barras apiladas los cuales amplian los gráficos de barras para poder comparar en dos variables categóricas al mismo tiempo."""

cross = pokemon[(pokemon['type_1'] == 'grass') | (pokemon['type_1'] == 'fire') | (pokemon['type_1'] == 'water')]
cross = pd.crosstab(cross['generation'], cross['type_1'])
cross

"""En un gráfico de barra comparativo para cada valor de la principal variable de agrupamiento(generación) se construye una cantidad de barras correspondiente a la cantidad de categorías de la segunda variable de agrupamiento(tipo). Este gráfico permite comparar las categorías de la segunda variable de agrupamiento dentro de cada categoría de la variable de agrupamiento principal con facilidad, pero como desventaja se pierde la percepción de la magnitud de cada una de las categorías en la variable de agrupamiento principal.

Aplicado lo anterior a este gráfico, en él resulta bastante simple distinguir cual es el tipo predominante dentro de cada generación, además de cual es la generación con más pokémon de un determinado tipo, pero no es para nada simple saber cuales son las generaciones con la mayor cantidad de pokemones de los tres tipos en conjunto.

Siempre que se pasen varias columnas al método <strong>".bar()"</strong> este va a construir un gráfico de barras comparativas.
"""


"""Por otra parte, un gráfico de barras apiladas construye una sola barra para cada categoría de la variable de agrupamiento principal(generación) y divide esta barra dependiendo de la magnitud de la medida en cada categoría de la variable de agrupamiento secundaria(tipo). En este tipo de gráfico se mantiene totalmente la percepción de la magnitud de las categorías de la variable de agrupamiento principal, y se tiene una idea de como la variable de agrupamiento secundaria se distribuye para cada categoría de la variable de agrupamiento principal, pero no tan claramente como en un gráfico de barras comparativas.

Lo anterior se puede observar dentro de este gráfico, en el cuál resulta sencillo observar cuales generaciones tienen más pokemones de los tres tipos en conjunto, pero es difícil observar por ejemplo, cual es la generación con la mayor cantidad de pokemones de tipo planta o cuál es el tipo predominante en la quinta generación.

Para crear un gráfico de barras apiladas al pasar múltiples columnas a <strong>".bar()"</strong> se debe especificar el parámetro "stacked" como True.
"""


"""### Gráfico de caja

Un gráfico de caja sencillo se utiliza para visualizar la distribución de una variable numérica. Este gráfico se basa en cuantiles. La línea en el centro de la caja corresponde a la mediana de la variable, los extremos de la caja son el cuantil 25 y 75, las líneas afuera de las cajas corresponden a las observaciones más alejadas que no estén a más de 1.5 veces el rango intercuartil de los extremos de la caja, cualquier observación que supere esta distancia se muestra como un círculo y se debe ver como un posible valor extremo.

Un gráfico de caja se crea con el método <strong>".boxplot()</strong> y a diferencia de los gráficos anteriores no se necesita el atributo <strong>".plot"</strong>. La variable a graficar se debe de especificar dentro del parámetro "column".
"""

pokemon.boxplot(column = 'sp_def')
plt.title('Distribution of Special Defense')
plt.xlabel('')
plt.ylabel('Special Defense')

plt.show()

"""Utilizando gráficos de caja también es posible visualizar la distribución de una variable numérica dentro de las distintas categorías de una variable categórica. Para hacer esto solo se debe de agregar el nombre de la variable categórica en el parámetro "by"."""

pokemon.boxplot(column = 'sp_def', by = 'generation', figsize = (7, 7))
plt.title('Distribution of Special Defense for each generation')
plt.xlabel('Generation')
plt.ylabel('Special Defense')

plt.show()

"""### Gráfico de línea

Los gráficos de línea se utilizan para visualizar la tendencia de una variable numérica a lo largo del tiempo, la variable que se usa en el eje x siempre debe de tener algún orden cronológico.

Para construir este gráfico se usa el método <strong>".line()"</strong>.

En este caso graficamos la misma información que en los gráficos de barras comparativas y apiladas, y es posible apreciar como en este gráfico es más fácil apreciar la tendencia de los diferentes tipos a lo largo de las generaciones.
"""


"""### Estilos

Dentro de matplotlib se incluyen estilos, los cuales modifican el formato general de todos los gráficos que se construyan. Estos estilos se aplican con la función <strong>"plt.style.use()"</strong>. La lista completa de estilos se encuentra en: https://matplotlib.org/gallery/style_sheets/style_sheets_reference.html

#### bmh
"""

plt.style.use('bmh')

cmap1 = matplotlib.colors.ListedColormap(['blue'])
cmap2 = matplotlib.colors.ListedColormap(['black'])
pokemon.loc[pokemon['generation'] == 1, 'attack'].plot.hist(bins = 10, cmap = cmap1, alpha = 0.5, legend = True)
pokemon.loc[pokemon['generation'] == 3, 'attack'].plot.hist(bins = 10, cmap = cmap2, alpha = 0.5, legend = True)
plt.legend(title = 'Generation', labels = ['1st', '3rd'], loc = 'center right')
plt.xlabel('Attack')
plt.title('Distribution of attack between the 1st and 3rd generation')

plt.show()


col = pokemon['generation'].value_counts(sort = False)
cmap = matplotlib.colors.ListedColormap(['black'])
col.plot.bar(rot = 0, cmap = cmap)
plt.xlabel('Generation')
plt.ylabel('Number of Pokémon')
plt.title('Number of Pokemon for each generation')

plt.show()

pokemon.boxplot(column = 'sp_def', by = 'generation', figsize = (7, 7))
plt.title('Distribution of Special Defense for each generation')
plt.xlabel('Generation')
plt.ylabel('Special Defense')

plt.show()


"""#### fivethirtyeight"""

plt.style.use('fivethirtyeight')

cmap1 = matplotlib.colors.ListedColormap(['blue'])
cmap2 = matplotlib.colors.ListedColormap(['black'])
pokemon.loc[pokemon['generation'] == 1, 'attack'].plot.hist(bins = 10, cmap = cmap1, alpha = 0.5, legend = True)
pokemon.loc[pokemon['generation'] == 3, 'attack'].plot.hist(bins = 10, cmap = cmap2, alpha = 0.5, legend = True)
plt.legend(title = 'Generation', labels = ['1st', '3rd'], loc = 'center right')
plt.xlabel('Attack')
plt.title('Distribution of attack between the 1st and 3rd generation')

plt.show()

col = pokemon['generation'].value_counts(sort = False)
cmap = matplotlib.colors.ListedColormap(['black'])
col.plot.bar(rot = 0, cmap = cmap)
plt.xlabel('Generation')
plt.ylabel('Number of Pokémon')
plt.title('Number of Pokemon for each generation')

plt.show()

pokemon.boxplot(column = 'sp_def', by = 'generation', figsize = (7, 7))
plt.title('Distribution of Special Defense for each generation')
plt.xlabel('Generation')
plt.ylabel('Special Defense')

plt.show()



"""#### seaborn"""

plt.style.use('seaborn-v0_8')

cmap1 = matplotlib.colors.ListedColormap(['blue'])
cmap2 = matplotlib.colors.ListedColormap(['black'])
pokemon.loc[pokemon['generation'] == 1, 'attack'].plot.hist(bins = 10, cmap = cmap1, alpha = 0.5, legend = True)
pokemon.loc[pokemon['generation'] == 3, 'attack'].plot.hist(bins = 10, cmap = cmap2, alpha = 0.5, legend = True)
plt.legend(title = 'Generation', labels = ['1st', '3rd'], loc = 'center right')
plt.xlabel('Attack')
plt.title('Distribution of attack between the 1st and 3rd generation')

plt.show()



col = pokemon['generation'].value_counts(sort = False)
cmap = matplotlib.colors.ListedColormap(['black'])
col.plot.bar(rot = 0, cmap = cmap)
plt.xlabel('Generation')
plt.ylabel('Number of Pokémon')
plt.title('Number of Pokemon for each generation')

plt.show()

#sp_defense
pokemon.boxplot(column = 'sp_def', by = 'generation', figsize = (7, 7))
plt.title('Distribution of Special Defense for each generation')
plt.xlabel('Generation')
plt.ylabel('Special Defense')

plt.show()

line = pokemon[(pokemon['type_1'] == 'grass') | (pokemon['type_1'] == 'fire') | (pokemon['type_1'] == 'water')]
line_cross = pd.crosstab(line['generation'], line['type_1'])

cmap = matplotlib.colors.ListedColormap(['red', 'green', 'blue'])
plt.title('Number of fire, grass and water Pokemon for each generation')
plt.xlabel('Generation')
plt.ylabel('Number of Pokemon')
plt.legend(title = 'Type', labels = ['Fire', 'Grass', 'Water'])

plt.show()

"""### Ejercicios de práctica.

1-) Elija un Pokémon de tipo Fire, tal que su habilidad de ataque especial esté por arriba del percentil 90% del ataque especial para este tipo de Pokémon, y qué tenga el máximo valor en against_water posible.

2-) En qué tipo de Pokémon la variable percentage_male es más baja en promedio? En este tipo de Pokémon, cómo ha sido la tendencia de crecimiento de esta variable en las diferentes generaciones?

3-) En qué tipo de Pokémon hay mayor porcentaje de Legendarios?

4-) Calcule la media de la variable 'speed' para los Pokémon agrupados por generación y  Type1. Qué tipo de Pokemón ha tenido mejoras en 'speed' en las diferentes generaciones?

5-) Cuántos Pokémon hay de un único tipo?

6-) Analice la tabla cruzada de las variables Type1 y Type2. Existe algún tipo de Type1 tal que la mayoría de sus type2 se encuentren en la misma categoría?

6-) Considerando la columna "total" definida en el notebook,

    pokemon['total'] = pokemon[['hp', 'attack', 'defense', 'speed', 'sp_attack', 'sp_defense']].sum(axis = 1)
de los Pokémon con valor en columna total menor al percentil 25% de esta columna, hay algún tipo de Type1 que sea más frecuente? y de Type2?

7-) Seleccione el Pokémon más pesado por generación. Encuentra algo interesante?

8-) Suponga en un torneo Pokemón solo se pueden usar Pokemón de tipo "bug","dark","dragon". Si cada equipo consta de 3 Pokemón, cuál cree usted que sería un buen equipo con la restricción que el equipo no puede pesar más de 300kg?
"""

