# -*- coding: utf-8 -*-
"""Limpieza_completa_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewztCSJJGfKgBtvfGOh5CvD6108aSybk
"""

import pandas as pd
import numpy as np

# ---------------------------------------------------------
# 1. Cargar data
# ---------------------------------------------------------
df = pd.read_csv("clientes_credito_raw.csv")

print("Vista general inicial:")
print(df.head())
print("\nInfo inicial:")
print(df.info())

# ---------------------------------------------------------
# 2. Detección de nulos y vacíos
# ---------------------------------------------------------

# Contar NaN
print("\nNulos por columna (NaN):")
print(df.isna().sum())

# Contar vacíos "" (muy frecuente en datos reales)
print("\nCeldas vacías por columna:")
blank_counts = (df == "").sum()
print(blank_counts)

# Unificar vacíos "" como NaN para tratarlos igual
df = df.replace(r"^\s*$", np.nan, regex=True)

print("\nNulos totales (NaN + vacíos unificados):")
print(df.isna().sum())

# ---------------------------------------------------------
# 3. Limpieza de variables categóricas (homologar valores)
# ---------------------------------------------------------

# 3.1. Campo 'sexo'
# Pasamos todo a minúsculas y quitamos espacios
df["sexo"] = df["sexo"].str.strip().str.lower()

# Definimos un diccionario de mapeo
sexo_map = {
    "m": "Masculino",
    "masc": "Masculino",
    "mascul": "Masculino",
    "masculino": "Masculino",
    "f": "Femenino",
    "fem": "Femenino",
    "femenino": "Femenino"
}

df["sexo"] = df["sexo"].map(sexo_map)

# 3.2. Campo 'ciudad'
df["ciudad"] = df["ciudad"].str.strip().str.lower()

ciudad_map = {
    "lima": "Lima",
    "lma": "Lima",
    "arequipa": "Arequipa",
    "trujillo": "Trujillo",
    "cusco": "Cusco",
    "cuzco": "Cusco",
    "piura": "Piura",
    "chiclayo": "Chiclayo"
}

df["ciudad"] = df["ciudad"].map(ciudad_map)

# 3.3. Campo 'nivel_estudios'
df["nivel_estudios"] = df["nivel_estudios"].str.strip().str.lower()

nivel_map = {
    "secundaria": "Secundaria",
    "secund.": "Secundaria",
    "tecnico": "Técnico",
    "técnico": "Técnico",
    "universitario": "Universitario",
    "univ.": "Universitario",
    "postgrado": "Postgrado",
    "post-grado": "Postgrado",
    "maestria": "Maestría",
    "maestría": "Maestría"
}

df["nivel_estudios"] = df["nivel_estudios"].map(nivel_map)

# 3.4. Campo 'tiene_mora'
df["tiene_mora"] = df["tiene_mora"].str.strip().str.lower()

mora_map = {
    "si": "Sí",
    "s": "Sí",
    "no": "No",
    "n": "No"
}

df["tiene_mora"] = df["tiene_mora"].map(mora_map)

print("\nValores únicos después de homologar:")
print("sexo:", df["sexo"].unique())
print("ciudad:", df["ciudad"].unique())
print("nivel_estudios:", df["nivel_estudios"].unique())
print("tiene_mora:", df["tiene_mora"].unique())

# ---------------------------------------------------------
# 4. Conversión de tipos y detección de problemas
# ---------------------------------------------------------

# Aseguramos que las numéricas realmente sean numéricas
num_cols = ["edad", "ingreso_mensual", "score_credito"]
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("\nInfo luego de conversión de tipos:")
print(df[num_cols].info())

# ---------------------------------------------------------
# 5. Imputación de valores faltantes
#    - Numéricas: media o mediana
#    - Categóricas: moda
# ---------------------------------------------------------

# 5.1. Imputación numérica
# Ejemplo: edad -> media, ingreso_mensual -> mediana, score_credito -> media
df["edad"] = df["edad"].fillna(df["edad"].mean().round(0))
df["ingreso_mensual"] = df["ingreso_mensual"].fillna(df["ingreso_mensual"].median())
df["score_credito"] = df["score_credito"].fillna(df["score_credito"].mean().round(0))

# 5.2. Imputación categórica con la moda (valor más frecuente)
cat_cols = ["sexo", "ciudad", "nivel_estudios", "tiene_mora"]

for col in cat_cols:
    moda = df[col].mode(dropna=True)
    if len(moda) > 0:
        df[col] = df[col].fillna(moda[0])

print("\nNulos después de imputar:")
print(df.isna().sum())

# ---------------------------------------------------------
# 6. Búsqueda de duplicados
# ---------------------------------------------------------

duplicados = df.duplicated().sum()
print(f"\nNúmero de filas duplicadas: {duplicados}")

# Si quieres eliminarlos:
df = df.drop_duplicates()

# ---------------------------------------------------------
# 7. Detección simple de outliers (Ejemplo con IQR)
# ---------------------------------------------------------

def detectar_outliers_iqr(serie):
    Q1 = serie.quantile(0.25)
    Q3 = serie.quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    return (serie < limite_inferior) | (serie > limite_superior)

for col in ["ingreso_mensual", "score_credito"]:
    outliers_mask = detectar_outliers_iqr(df[col])
    print(f"\nOutliers en {col}: {outliers_mask.sum()}")

    # Opcional: puedes "capear" valores extremos a los límites
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    df[col] = np.where(df[col] < limite_inferior, limite_inferior, df[col])
    df[col] = np.where(df[col] > limite_superior, limite_superior, df[col])

# ---------------------------------------------------------
# 8. Resultado final
# ---------------------------------------------------------

print("\nData limpia (primeras filas):")
print(df.head())

try:
    # Guardar dataset limpio
    df.to_csv("clientes_credito_limpio.csv", index=False, encoding="utf-8")
    print("\nArchivo limpio guardado como 'clientes_credito_limpio.csv'")
except Exception as e:
    print("archivo creado", e)